stages:
  - install
  - build
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"

image: node:22

before_script:
  - apt-get update
  - apt-get install -y wget gnupg
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update
  - apt-get install -y google-chrome-stable
  - npm install -g @angular/cli
  - npm ci

install_dependencies:
  stage: install
  script:
    - echo "Dependencies installed"

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test:
  stage: test
  script:
    - npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/junit-report.xml
